### ISSUE TITLE
Releases with SDTV specified are upping as HDTV

### ISSUE THREAD

**Issue by pmow** [midgetspy/Lift-Cup#7]
In my case I am using:
python lc.py --nocleanup TITLE.S01E01.avi SDTV

And Lift-Cup is appending HDTV, where SDTV or PDTV might go.

**Comment by midgetspy** [comment]
I assume you mean HDTV.XviD which is the standard source/format for SD TV...

**Comment by pmow** [comment]
Well, if not taken from "HDTV" it should be DSR or PDTV.  The HDTV source tag is for HDTV sources.  You don't agree?

**Comment by midgetspy** [comment]
You're not picking the source, you're picking the quality. The intention of this tool was so SB would recognize uploads, so HDTV.XviD is used for SD by default. If you want it to be correct and it's not HDTV.XviD then you'll have to just rename it according to the source & format manually.

**Comment by pmow** [comment]
Perfect, thanks.
